### ISSUE TITLE
明明查询成功却提示查询出错

### ISSUE THREAD

**Issue by CYDXDianXian** [azmiao/pcrjjc3-tw#12]
![0A0C439D-4845-4519-954F-A4B6B6F28316](https://user-images.githubusercontent.com/71607036/159867767-b3ae8420-ac21-4633-aa0d-ce3b8383fb0d.jpeg)

**Comment by azmiao** [comment]
坏了

**Comment by azmiao** [comment]
哦对了，hso

**Comment by azmiao** [comment]
我不理解，不能这样写吗2333，不是都finish了吗，而且详细查询也不会报错，为啥竞技场查询会这样嘞，电线佬救命
```
            await bot.finish(ev, 
f'''区服：{cx_name}
昵称：{res['user_info']["user_name"]}
jjc排名：{res['user_info']["arena_rank"]}
pjjc排名：{res['user_info']["grand_arena_rank"]}
最后登录：{last_login_str}''', at_sender=False)
        except ApiException as e:
            await bot.finish(ev, f'查询出错，{e}', at_sender=True)
        except requests.exceptions.ProxyError:
            await bot.finish(ev, f'查询出错，连接代理失败，请再次尝试', at_sender=True)
        except:
            await bot.finish(ev, f'查询出错，请再次尝试', at_sender=True)
```

**Comment by CYDXDianXian** [comment]
稍等，我看看

**Comment by azmiao** [comment]
> 稍等，我看看

啊这， 我print了一下看了一下，显示的是：
ServiceFunc of HoshinoBot finished.

**Comment by azmiao** [comment]
芝，解决了，把发送竞技场查询结果的那条消息改成bot.send就好了23333

**Comment by CYDXDianXian** [comment]
> 芝，解决了，把发送竞技场查询结果的那条消息改成bot.send就好了23333

改了依然会出问题
![image](https://user-images.githubusercontent.com/71607036/159873062-af85110c-05bc-4d73-8c8a-7b2edf419e02.png)

**Comment by azmiao** [comment]
> > 芝，解决了，把发送竞技场查询结果的那条消息改成bot.send就好了23333
> 
> 改了依然会出问题 ![image](https://user-images.githubusercontent.com/71607036/159873062-af85110c-05bc-4d73-8c8a-7b2edf419e02.png)

欸，奇怪了，我这没问题了
![Snipaste_2022-03-24_16-23-34](https://user-images.githubusercontent.com/54100327/159873488-5ad7face-2e71-4289-a87f-92ac4cc66c86.png)

**Comment by CYDXDianXian** [comment]
哦对，合适，这样没问题

**Comment by azmiao** [comment]
> 哦对，合适，这样没问题

23333，但原因是为啥呢，星乃的hoshino里面我看了下那个_finish()，感觉也没问题啊hhhh

**Comment by CYDXDianXian** [comment]
bot.send和bot.finish的区别是啥呀？我也不明白。。。

**Comment by azmiao** [comment]
> bot.send和bot.finish的区别是啥呀？我也不明白。。。

hhhh原来你也不知道，应该是finish发完就会直接停止了吧，感觉类似send后return，这应该是咖啡佬自己加的，我在nonebot和aiocqhttp里面都没有找到

**Comment by CYDXDianXian** [comment]
> > bot.send和bot.finish的区别是啥呀？我也不明白。。。
> 
> hhhh原来你也不知道，应该是finish发完就会直接停止了吧，感觉类似send后return，这应该是咖啡佬自己加的，我在nonebot和aiocqhttp里面都没有找到

原来如此！阿梓喵tql！

**Comment by azmiao** [comment]
> > > bot.send和bot.finish的区别是啥呀？我也不明白。。。
> > 
> > 
> > hhhh原来你也不知道，应该是finish发完就会直接停止了吧，感觉类似send后return，这应该是咖啡佬自己加的，我在nonebot和aiocqhttp里面都没有找到
> 
> 原来如此！阿梓喵tql！

啊不，这是我猜的（），因为平时就当这样用的好像没啥问题，但像这次的报错我就很不能理解了hhhh
