### ISSUE TITLE
我想问新的这个支持B服吗

### ISSUE THREAD

**Issue by zhtyirg3** [azmiao/pcrjjc3-tw#13]
大佬问一下，我是新手，可能不是很懂。
1cx_com.bilibili.priconne.v2.playerprefs.xml 复制到PJJC3的目录里，不启动代理，重启HOSHINO，机器人回复一切正常，输入指令竞技场帮助正常，但是就是绑定不了ID。输入指令 竞技场绑定 1 ID，后台完全没有回复，也没有出错记录。是哪一步不对吗？还是插件不支持B服？
![LWIW~~V8_IZ)}$OA_M Q _J](https://user-images.githubusercontent.com/55908974/163657301-9bd741d5-c786-4b32-acf1-2183af6120b7.png)

**Comment by azmiao** [comment]
啊这哈哈哈，是的哟，这是台服竞技场查询的，你看pcrjjc3后面不是有个tw代表台服，然后仓库的简介里也写了台服的，如果你需要国服请去pcrjjc2，找到主分支，主分支是国服的
