### ISSUE TITLE
4月某天以后不推送可查询.求解

### ISSUE THREAD

**Issue by policecalvin** [azmiao/pcrjjc3-tw#14]
具体日期没记住,某天以后新增的用户都不推送排名,原添加的会推送
但是所有人都可以查询排名,就是不推送排名降低.启用竞技场订阅也是一样.求解

**Comment by azmiao** [comment]
请检查一下binds.json文件里是否有新增用户的QQ号，另外自动推送查询时后台日志是否有报错

**Comment by policecalvin** [comment]
> 请检查一下binds.json文件里是否有新增用户的QQ号，另外自动推送查询时后台日志是否有报错

发现了原因...因为我只有一个台二的配置文件,然后有人绑定了台三的角色
每次轮巡查排名变动的时候,查到那个台三的角色就直接终止操作了....

**Comment by policecalvin** [comment]
轮巡查询应该少了一个判定.建议加一个

**Comment by azmiao** [comment]
> 轮巡查询应该少了一个判定.建议加一个

ok,这就加

**Comment by azmiao** [comment]
> 轮巡查询应该少了一个判定.建议加一个

哦，原来是有这个判定的，但代码写的不太对
