### ISSUE TITLE
详细查询出错

### ISSUE THREAD

**Issue by Azusa-Yuan** [azmiao/pcrjjc3-tw#15]
我对协程异步这些还不是很了解，没有改过详细查询的代码，查了下还是不清楚为什么没有事件在协程里。希望大佬能教教我，谢谢。
出问题的语句
![图片](https://user-images.githubusercontent.com/61765965/168513785-8e2401a6-b84b-478c-ad46-4623d59d90b7.png)
错误情况
![图片](https://user-images.githubusercontent.com/61765965/168514070-67a426aa-d39a-40e7-b93f-56d1ce97f210.png)
后台的情况
![图片](https://user-images.githubusercontent.com/61765965/168514109-d3037d28-9b08-4044-b5f6-6e0d00af2d80.png)

**Comment by CYDXDianXian** [comment]
错误不是出在这里，这语句没任何问题，请提供具体的错误日志，谢谢

**Comment by Azusa-Yuan** [comment]
> 错误不是出在这里，这语句没任何问题，请提供具体的错误日志，谢谢
感谢您的回复，这是我去掉try之后显示的错误
![图片](https://user-images.githubusercontent.com/61765965/168515116-b5d8f7c6-b0d4-4c0e-930e-1c2989fb22f7.png)

**Comment by Azusa-Yuan** [comment]
我好像发现是我少开模块了，我去打开试试
打开priconne模块后依旧出错

**Comment by CYDXDianXian** [comment]
终极办法，把hoshino更新到最新版，如果魔改过hoshino，直接覆盖更新。版本过老的hoshino难免出现各种问题。

**Comment by Azusa-Yuan** [comment]
已经更新到最新的版本，还是无法解决

**Comment by Azusa-Yuan** [comment]
> 终极办法，把hoshino更新到最新版，如果魔改过hoshino，直接覆盖更新。版本过老的hoshino难免出现各种问题。

您好，我解决该问题了，是图片库没有更新到最新版，导致挂最新角色头像账号的详细查询没法使用

**Comment by azmiao** [comment]
> > 终极办法，把hoshino更新到最新版，如果魔改过hoshino，直接覆盖更新。版本过老的hoshino难免出现各种问题。
> 
> 您好，我解决该问题了，是图片库没有更新到最新版，导致挂最新角色头像账号的详细查询没法使用

嗯~图片库是指pillow库吗2333

**Comment by Azusa-Yuan** [comment]
> > > 终极办法，把hoshino更新到最新版，如果魔改过hoshino，直接覆盖更新。版本过老的hoshino难免出现各种问题。
> > 
> > 
> > 您好，我解决该问题了，是图片库没有更新到最新版，导致挂最新角色头像账号的详细查询没法使用
> 
> 嗯~图片库是指pillow库吗2333

是指PCR角色头像图片库啦，合成功能要用到hoshino priconne模块的chara.py，没有对应的角色头像图片会报错

**Comment by azmiao** [comment]
> > > > 终极办法，把hoshino更新到最新版，如果魔改过hoshino，直接覆盖更新。版本过老的hoshino难免出现各种问题。
> > > 
> > > 
> > > 您好，我解决该问题了，是图片库没有更新到最新版，导致挂最新角色头像账号的详细查询没法使用
> > 
> > 
> > 嗯~图片库是指pillow库吗2333
> 
> 是指PCR角色头像图片库啦，合成功能要用到hoshino priconne模块的chara.py，没有对应的角色头像图片会报错

哦哦，那ok了，issue我就关掉咯
