### ISSUE TITLE
有时灵有时不灵

### ISSUE THREAD

**Issue by Sylphinford** [azmiao/pcrjjc3-tw#16]
有时候有用，重启后失效。重启N次后又有用了。。非常玄学。
当前处于重启N次依然失败的状态，只能求助了

看日志应该是加载了
![QQ截图20220525114227](https://user-images.githubusercontent.com/43917892/170233013-d168c9db-3ff3-426c-ae14-082bf9d200bf.png)

命令识别了，但后续没有发送任何内容
![QQ截图20220525114406](https://user-images.githubusercontent.com/43917892/170233384-047d1a63-2c36-4b90-a9bb-4128da16449a.png)

海外，无代理

**Comment by azmiao** [comment]
看起来确实没有问题，没有报错，日志也正常运行完成了。请首先确保该群启用了竞技场推送功能，另外可以看看gocqhttp的控制台看看有没有显示什么问题。

**Comment by Sylphinford** [comment]
这是对应的go日志。
![QQ截图20220525133534](https://user-images.githubusercontent.com/43917892/170253134-00dca3c8-17eb-4a24-a34f-c64a2c8209a2.png)
bot收到后，不回复任何内容

**Comment by azmiao** [comment]
> 这是对应的go日志。 ![QQ截图20220525133534](https://user-images.githubusercontent.com/43917892/170253134-00dca3c8-17eb-4a24-a34f-c64a2c8209a2.png) bot收到后，不回复任何内容

你这就很怪，你这个群里确认开启了这个服务吗

**Comment by Sylphinford** [comment]
真的很玄学，有时候有用的，没有对bot改动，重启后就没用了。重启几次有时候又有用。。
现在处于没用的状态

![QQ截图20220525140426](https://user-images.githubusercontent.com/43917892/170259195-562a4867-2778-48dc-8d4b-147a648122fb.png)
![QQ截图20220525140306](https://user-images.githubusercontent.com/43917892/170259201-063d89a0-5c5d-4a57-8c0d-8d1a0738cb70.png)
![QQ截图20220525140929](https://user-images.githubusercontent.com/43917892/170259205-59fa9041-e49a-4b4e-9e6c-11da0da74908.png)

**Comment by azmiao** [comment]
我怀疑可能是finish的问题，要不试试把`hoshino/\_\_init\_\_`更新至最新的

**Comment by azmiao** [comment]
emmm尝试了各种方案测试，貌似都没有问题，话说你有时候能用有时候不能用，说不定是你的海外服务器有时候也连不上游戏？要不尝试添加代理试试？其他我也想不到了23333

**Comment by azmiao** [comment]
可以去[pcrjjc2-tw分支](https://github.com/cc004/pcrjjc2/tree/tw)问问原作者[cc004](https://github.com/cc004)可能的原因

**Comment by azmiao** [comment]
顺便 @CYDXDianXian 看看电线佬有啥想法吗

**Comment by CYDXDianXian** [comment]
不用代理的话把代理留空，海外服务器必须是港服或者台服才能直连。其他的我实在想不到了。没法复现这样的问题，无从下手23333

**Comment by Sylphinford** [comment]
感觉不是代理问题，因为不是连不上，是完全不进行操作。
用的这个BOT，不知道能不能从这里找到原因
https://github.com/pcrbot/hoshino_xcw

**Comment by azmiao** [comment]
> 感觉不是代理问题，因为不是连不上，是完全不进行操作。 用的这个BOT，不知道能不能从这里找到原因 https://github.com/pcrbot/hoshino_xcw

啊这，是xcw，这边强烈建议使用原版，建议使用原版试试，如果由于使用修改版本导致的问题请自行研究解决

**Comment by azmiao** [comment]
这边先关闭issue了，如果后续使用原版仍有问题，可以再次开启issue
