### ISSUE TITLE
竞技场关注和上线提醒功能

### ISSUE THREAD

**Issue by Mira19971102** [azmiao/pcrjjc3-tw#17]
求电线佬缝一个可以竞技场关注和提醒对手上线的功能
![0D7D76E7E7378AF2A11AC924E6D31A55](https://user-images.githubusercontent.com/118086097/201500297-9a0a9ca6-5013-491f-9fd4-7ae0bfd91eed.jpg)

**Comment by azmiao** [comment]
虽然我个人是不希望这样的，避免争锋。防止祸水东引，但线宝要是想加那就加吧 @CYDXDianXian

**Comment by Mira19971102** [comment]
额，那还是不加吧，线宝说非常的浪费流量（开代理的话）
