### ISSUE TITLE
game_start api failed code = 204

### ISSUE THREAD

**Issue by Cruelmoon** [azmiao/pcrjjc3-tw#18]
更新后发现无法请求登录游戏了，api报错。
`pcrclient: /check/game_start api failed code = 204, {'status': 3, 'title': '伺服器錯誤', 'message': '遊戲發生錯誤。\\n即將返回標題畫面。'}`

**Comment by azmiao** [comment]
看一下`headers.json`，看看版本号是不是最新的3.6.0，我这边测试没问题

**Comment by Cruelmoon** [comment]
看了，是版本号问题。改成`3.6.0`就好了。我维护前把机器人关了，所以没有获取到最新的版本号
感谢解答!
