### ISSUE TITLE
请问这个竞技场角色名在哪手动更新的。。

### ISSUE THREAD

**Issue by Mira19971102** [azmiao/pcrjjc3-tw#19]
![$C8XAX8% 6S_){ACWJWQKDP](https://user-images.githubusercontent.com/118086097/210195431-c81fe320-cb48-4ed1-bc8c-f85148399d76.PNG)

**Comment by azmiao** [comment]
使用星乃自带的角色数据，hoshino\modules\priconne下的\_pcr\_data.py，如果不想手动更新，可以尝试使用这个https://github.com/pcrbot/gacha

**Comment by Mira19971102** [comment]
谢谢大佬
