### ISSUE TITLE
查询时报错

### ISSUE THREAD

**Issue by dyx-max** [azmiao/pcrjjc3-tw#20]
pcrclient: /check/game_start api failed code = 208, {'status': 5, 'title': '伺服器錯誤', 'message': '資料處理發生錯誤。'}

**Comment by azmiao** [comment]
本次的apkimage.io版本更新较慢，导致无法及时同步到插件中，您可在`headers.json`先将版本号手动更新为3.7.0，然后无需重启bot直接使用插件

**Comment by dyx-max** [comment]
问题已解决，多谢

**Comment by azmiao** [comment]
原来的版本号源老是不更新，打算更换版本号源
