### ISSUE TITLE
查询时出错

### ISSUE THREAD

**Issue by dyx-max** [azmiao/pcrjjc3-tw#21]
pcrclient: /load/index api failed code = 501, {'status': 3, 'title': '伺服器錯誤', 'message': '遊戲發生錯誤。\\n即將返回標題畫面。'}

**Comment by azmiao** [comment]
抱歉哈，你的issue之前没收到邮件提醒，现在才看到，你这个一般是版本号不对，之前获取版本号的网站寄了，现在已经换了一个，你可以更新一下，然后每天13点会自动更新的，另外如果想实时生效，可以吧`headers.json`中的版本号改为最新的版本
