### ISSUE TITLE
向搜内服务器api发送请求出错

### ISSUE THREAD

**Issue by Cruelmoon** [azmiao/pcrjjc3-tw#24]
错误如下：
pcrclient: /check/game_start api failed code = 2, {'status': 3, 'title': '伺服器錯誤', 'message': '遊戲發生錯誤。\n即將返回標題畫面。'}

我有试着吧headers.json改成
`"APP-VER": "3.8.0"`
但是还是提示failed code = 2

**Comment by azmiao** [comment]
可能是代理不行了？尝试换个代理/节点试试，话说你是第一次使用吗，还是之前正常用过，我这边现在测试还是没问题

**Comment by Cruelmoon** [comment]
我昨天维护前能正常使用，但是更新后就不行了

**Comment by azmiao** [comment]
> 我昨天维护前能正常使用，但是更新后就不行了

你看看你的代理节点也没有被搜内ban，可以换个节点或代理试试我这测试一直都没啥问题，另外还可以等一下你的机器人账号看看，你的游戏账号也没有被封之类的

**Comment by Cruelmoon** [comment]
我在本地测了一下就没问题，在服务器上不行。感觉是得换个ip了。感谢解答
