### ISSUE TITLE
有几个导致项目跑不起来的bug

### ISSUE THREAD

**Issue by Co1dF1sh** [azmiao/pcrjjc3-tw#28]
调试了一下，改了几段代码就能跑了

不改的话应该是跑不起来的

#### 1. query api错误

​	这个bug我没找到逻辑错在哪，反正就是在请求的时候并没有请求api5-pc.so-net.tw这个新api，请求的还是老的api，比如api2-pc.so-net.tw

​	解决方案：呃，我懒狗，直接把pcrclient.py里的apiroot给写死到api5-pc.so-net.tw了

#### 2. init.py里查询逻辑没改

​	现在新id是10位了，加的第1位是原来的服务器编号。然后init.py里的正则要改成10位数字的正则，9位数字查不起来，会报用户不存在

有大佬闲的话可以修改一下 我就不把我东拼西凑的垃圾代码提交上来了

**Comment by Co1dF1sh** [comment]
还有 猫哥yyds 这么快就整出来了 想给猫哥舔牛子

**Comment by sdyxxjj123** [comment]
都是些很蠢的错误，已经修正

**Comment by azmiao** [comment]
新的[pcrjjc_tw_new](https://github.com/azmiao/pcrjjc_tw_new)已经可以自动兼容新旧配置文件和自动改uid了，可以测试一下试试，适配还得是2佬牛逼
